### ISSUE TITLE
Git Hub Repository actions settings need to change to allow actions to create a release

### ISSUE THREAD

**Issue by ajgrah2000** [ChrisAlphabet/ghost-bot#8]
gost-bat -> settings -> general -> Actions -> General
Workflow permissions
Enable -> Read and write permissions 

They're presumably currently set to 'read permissions'

There may be a 'better' way, but that should work.

**Comment by ChrisAlphabet** [comment]
Success! 
https://github.com/ChrisAlphabet/ghost-bot/releases/tag/main_e818937eccdf732055163b64073c3a9e36451fbf 
Thanks :)
